### ISSUE TITLE
i wonder how to creat a task and a robot of my own , i dont even know what the numbers means in the example

### ISSUE THREAD

**Issue by SamSAM-WWW** [JiahengHu/GLSO#1]
i wonder how to creat a task and a robot of my own using robogrammar , i dont even know what the numbers means in the example given by the Robogrammar such as python3 examples/design_search/viewer.py RidgedTerrainTask data/designs/grammar_apr30.dot -j8 0, 7, 1, 13, 1, 2, 16, 12, 13, 6, 4, 19, 4, 17, 5, 3, 2, 16, 4, 5, 18, 9, 8, 9, 9, 8 -o

**Comment by JiahengHu** [comment]
This issue should probably be posted in the original RoboGrammar repo.
Here is the place you can define your task: https://github.com/JiahengHu/RoboGrammar/blob/main/examples/design_search/tasks.py
The numbers mean a sequence of grammar rules that are applied to obtain a specific design.
